"""CompositeEngine — 跨市场组合引擎。

共享资金池，委托子引擎规则方法。
"""

from __future__ import annotations

from typing import Dict

import pandas as pd

from .base import BaseEngine
from .china_a import ChinaAEngine
from .crypto import CryptoEngine
from .forex import ForexEngine
from .global_equity import GlobalEquityEngine
from .models import Position


def _detect_market_simple(symbol: str) -> str:
    """简化版市场检测。"""
    if "." in symbol:
        suffix = symbol.split(".")[-1].upper()
        if suffix in ("SZ", "SH", "BJ"):
            return "a_share"
        if suffix == "HK":
            return "hk_equity"
        if suffix in ("NS", "BO"):
            return "india_equity"
    if "-" in symbol or "/" in symbol:
        return "crypto"
    # Forex pairs: 6 alphabetic chars (e.g. EURUSD, GBPJPY)
    if len(symbol) == 6 and symbol.isalpha():
        return "forex"
    if len(symbol) <= 5 and symbol.isalpha():
        return "us_equity"
    return "a_share"


class CompositeEngine(BaseEngine):
    """跨市场组合引擎：共享资金池 + 委托子引擎规则。"""

    def __init__(self, config: dict, codes: list[str]):
        super().__init__(config)
        self._symbol_market = {c: _detect_market_simple(c) for c in codes}
        self._rule_engines: Dict[str, BaseEngine] = self._build_rule_engines(config)
        # Crypto dedup state
        self._funding_applied: set = set()
        self._funding_daily_done: set = set()
        # Forex dedup state
        self._last_swap_dates: dict = {}

    def _build_rule_engines(self, config: dict) -> Dict[str, BaseEngine]:
        return {
            "a_share": ChinaAEngine(config),
            "us_equity": GlobalEquityEngine(config, market="us"),
            "hk_equity": GlobalEquityEngine(config, market="hk"),
            "crypto": CryptoEngine(config),
            "forex": ForexEngine(config),
        }

    def _rule_for(self, symbol: str) -> BaseEngine:
        market = self._symbol_market.get(symbol, "a_share")
        return self._rule_engines.get(market, self._rule_engines["a_share"])

    def can_execute(self, symbol: str, direction: int, bar: pd.Series) -> bool:
        market = self._symbol_market.get(symbol, "a_share")
        # T+1 interceptor for A-share
        if market == "a_share" and direction == 0:
            pos = self.positions.get(symbol)
            if pos is not None:
                bar_date = bar.name.date() if hasattr(bar, "name") else None
                entry_date = pos.entry_time.date() if hasattr(pos.entry_time, "date") else None
                if bar_date and entry_date and bar_date == entry_date:
                    return False
        return self._rule_for(symbol).can_execute(symbol, direction, bar)

    def round_size(self, raw_size: float, price: float) -> float:
        return self._rule_for(self._active_symbol).round_size(raw_size, price)

    def calc_commission(self, size: float, price: float, direction: int, is_open: bool) -> float:
        return self._rule_for(self._active_symbol).calc_commission(size, price, direction, is_open)

    def apply_slippage(self, price: float, direction: int) -> float:
        sub = self._rule_for(self._active_symbol)
        return sub.apply_slippage(price, direction)

    def _calc_pnl(self, symbol, direction, size, entry_price, exit_price):
        return self._rule_for(symbol)._calc_pnl(symbol, direction, size, entry_price, exit_price)

    def _calc_margin(self, symbol, size, price, leverage):
        return self._rule_for(symbol)._calc_margin(symbol, size, price, leverage)

    def on_bar(self, symbol: str, bar: pd.Series, timestamp: pd.Timestamp) -> None:
        market = self._symbol_market.get(symbol)
        if market == "crypto":
            # Delegate to CryptoEngine.on_bar with shared state
            crypto_sub = self._rule_engines["crypto"]
            self._run_subengine_on_bar(crypto_sub, symbol, bar, timestamp)
        elif market == "forex":
            # Delegate to ForexEngine.on_bar with shared state
            forex_sub = self._rule_engines["forex"]
            self._run_subengine_on_bar(forex_sub, symbol, bar, timestamp)

    def _run_subengine_on_bar(
        self, sub: BaseEngine, symbol: str, bar: pd.Series, timestamp: pd.Timestamp
    ) -> None:
        """Run sub-engine's on_bar with shared capital/positions state."""
        # Share state references so sub-engine operates on composite state
        sub.capital = self.capital
        sub.positions = self.positions
        sub._bar_idx = self._bar_idx
        sub.on_bar(symbol, bar, timestamp)
        # Sync state back (positions/capital are mutated in place; trades appended)
        self.capital = sub.capital
        # Merge trades generated by sub-engine into composite's trade list
        self.trades.extend(sub.trades)
        sub.trades.clear()


__all__ = ["CompositeEngine"]